### PR TITLE
Put global actions into a menu

### PR DESCRIPTION
**Pull request by pgiraud**

### CODE REVIEW

**Comment by pgiraud** [comment]
@rjuju What do you think about this enhancement?

Screenshot from 2023-07-06 09-18-37

**Comment by rjuju** [comment]
I like it!  FTR I try to keep the model changes as small as possible to avoid conflicts on this branch, but I greatly welcome any improvement there.

I don't know if you noticed yet but I also pushed a new (probably conflicting) change around there to hide all those buttons if the logged-in user isn't allowed to use them (the new handler.notify_allowed).  Note that the same security check is enforced on the collector side, it's just to avoid unnecessary rountrips between the UI and the collector when you know they won't be allowed anyway.

**Comment by pgiraud** [comment]
> I like it! FTR I try to keep the model changes as small as possible to avoid conflicts on this branch, but I greatly welcome any improvement there.
> 
> I don't know if you noticed yet but I also pushed a new (probably conflicting) change around there to hide all those buttons if the logged-in user isn't allowed to use them (the new handler.notify_allowed). Note that the same security check is enforced on the collector side, it's just to avoid unnecessary rountrips between the UI and the collector when you know they won't be allowed anyway.

Changes taken into account.

**Comment by rjuju** [comment]
Great, thanks a lot!

**Pull request merged**
