### PR TITLE
Show grid lines in charts

### PR DESCRIPTION
**Pull request by pgiraud**
Vertical lines + horizontal lines matching the ticks for the left Y axis.

### CODE REVIEW

**Comment by pirlgon** [comment]
In previous version both of the left and right axis value where aligned with the grid (with unrounded values) not sure if it's needed

**Comment by pgiraud** [comment]
> In previous version both of the left and right axis value where aligned with the grid (with unrounded values) not sure if it's needed

Indeed, but I don't think it was a good idea.

I decided not to use horizontal lines at all because when we have several Y axis I couldn't get the ticks to be aligned. I tried but couldn't get something satisfying. For the record, seems like even the Grafana team didn't find a good way to handle this. It looks like they show horizontal lines for only one of the axis.

The previous charting library (RickShaw) is aligning ticks but in some cases, the range for one the axis is way too large and the series may be squashed to the bottom of the chart and thus difficult to read.
   
For example, in the image below, given the range of the right axis, the data is easier to compare on the new version (left) specifically for the "queries per sec" serie (blue).

Screenshot from 2023-05-05 12-32-56


@rjuju thoughts?

**Comment by rjuju** [comment]
Would it be possible to show the horizontal lines if there's a single Y axis?

One thing I often do with a graph with series on totally different scale is hide everything except the serie I want to look at (which can be done in a single click in the old interface by clicking on the serie name rather than the tick), and then the graph automatically adapt the Y axis range, making the values easy to read.  In such case (or if you select multiple series with the same unit), showing the horizontal lines are helpful.

**Comment by pgiraud** [comment]
With the latest version of this branch, we now have:
 - vertical grid lines,
 - the ability to choose the series to display (using `ctrl` key is possible to choose more than one), only one axis will display when relevant, axis ranges automatically adapt to selection,
 - horizontal grid lines for one axis (the left one unless only the right axis is displayed).

Screenshot from 2023-05-10 22-35-05
Screenshot from 2023-05-10 22-35-17
Screenshot from 2023-05-10 22-36-51

**Comment by rjuju** [comment]
@pgiraud sorry to come back so late on that.

> the ability to choose the series to display (using ctrl key is possible to choose more than one), only one axis will display when relevant, axis ranges automatically adapt to selection,

Unfortunately, this doesn't work on macos.  Apple is famous to make really ludicrous decisions on a daily basis, and if you're one of the happy people that aren't forced to work on that joke they call an OS, I have to inform you that they thought that it would be a good idea to have "ctrl-click" means "right-click".  Yes...  Maybe we could use "alt-click" for the multi-selection too?  With a bit of luck they won't decide map it to double click or something else before I can finally have a decent laptop back.

**Comment by pgiraud** [comment]
> @pgiraud sorry to come back so late on that.
> 
> > the ability to choose the series to display (using ctrl key is possible to choose more than one), only one axis will display when relevant, axis ranges automatically adapt to selection,
> 
> Unfortunately, this doesn't work on macos. Apple is famous to make really ludicrous decisions on a daily basis, and if you're one of the happy people that aren't forced to work on that joke they call an OS, I have to inform you that they thought that it would be a good idea to have "ctrl-click" means "right-click". Yes... Maybe we could use "alt-click" for the multi-selection too? With a bit of luck they won't decide map it to double click or something else before I can finally have a decent laptop back.

Now fixed in latest version of the `switch_backbone_vue_vite` branch.

**Comment by rjuju** [comment]
Thanks a lot!

FTR I just realized that apple doesn't have an "alt" key (I'm always using an external normal keyboard, can't stand the apple one), so it actually got mapped to the "super" key.  Anyway, works like a charm!

**Pull request merged**
